export const cardHoldersNameFieldName = 'cardHoldersName'
export const cardNumberFieldName = 'cardNumber'
export const expirationDateFieldName = 'expirationDate'
export const cvcFieldName = 'cvc'
export const addressPostalCodeFieldName = 'addressPostalCode'
