import Document, { DocumentContext } from 'next/document'
import { ServerStyleSheet as SCServerStyleSheet } from 'styled-components'
import { ServerStyleSheets as MuiServerStyleSheet } from '@mui/styles'

/**
 * Adds Server-side Rendering support for stylesheets
 * generated by both Styled-Components & MaterialUI.
 *
 * Next.js' _document page allows us to customize the
 * final HTML output produced by the framework.
 * @see https://nextjs.org/docs/advanced-features/custom-document
 */
export default class MyDocument extends Document {
    static async getInitialProps(ctx: DocumentContext) {
        const scSheet = new SCServerStyleSheet()
        const muiSheet = new MuiServerStyleSheet()
        const originalRenderPage = ctx.renderPage

        try {
            ctx.renderPage = () =>
                originalRenderPage({
                    enhanceApp: (App) => (props) =>
                        scSheet.collectStyles(
                            muiSheet.collect(<App {...props} />)
                        ),
                })

            const initialProps = await Document.getInitialProps(ctx)
            return {
                ...initialProps,
                styles: (
                    <>
                        {initialProps.styles}
                        {muiSheet.getStyleElement()}
                        {scSheet.getStyleElement()}
                    </>
                ),
            }
        } finally {
            scSheet.seal()
        }
    }
}
